version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pg_students
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: students_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: students_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
